// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb1PkUkt2eavsT6uYABjQnJ9dFsQv2aug',
    appId: '1:279273359642:android:c26979be91e20d71e204a3',
    messagingSenderId: '279273359642',
    projectId: 'rst-office-chat',
    storageBucket: 'rst-office-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn6Nq2fFQ_rHQdyYVMUxYIMrIU-EZGx54',
    appId: '1:279273359642:ios:104eb340e270e971e204a3',
    messagingSenderId: '279273359642',
    projectId: 'rst-office-chat',
    storageBucket: 'rst-office-chat.firebasestorage.app',
    androidClientId: '279273359642-lugn7kaunfo0hbkqrqcp65b79ej4qncq.apps.googleusercontent.com',
    iosClientId: '279273359642-qhcr2bh7f67dpiifo3vsmk81dpjs00kd.apps.googleusercontent.com',
    iosBundleId: 'com.rst.officechat.rstChatApp',
  );
}
